# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

RcppOwenQ1 <- function(nu, t, delta, R, Tha) {
    .Call('OwenR_RcppOwenQ1', PACKAGE = 'OwenR', nu, t, delta, R, Tha)
}

